name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: password
      DATABASE_URL: postgres://postgres:password@localhost:5432/test

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Set up DB
        run: |
          cp config/database.yml.github config/database.yml
          bundle exec rails db:create db:migrate
      - name: Run tests
        run: bundle exec rspec
